const langs = {
  en: {
    name: "English",
    strings: {
      "app.title": "Playspace Whiteboard",
      "app.beta.buildwarning":
        "<strong>You are using an BETA build of Playspace Whiteboard, which means you may experience severe stability issues.</strong> Therefore, we do not recommend using this build for any actual work.<br/><br/>Please remember to report any issues you face.<br/>You can disable this message by setting the flag ShowBuildWarning to Disabled.",
      "app.tool.isReady": "is ready",
      "app.tool.isSelected": "is selected",
      "app.tool.pan": "Pan",
      "app.tool.pen": "Pen",
      "app.tool.highlighter": "Highlighter",
      "app.tool.eraser": "Eraser",
      "app.action.undo": "Undo",
      "app.action.redo": "Redo",
      "app.action.collabmodule.managecollab": "Manage People",
      "app.notice.menubeta": "Beta Information",
      "app.header.managePeople": "Manage collaboration",
      "app.header.more": "More options",
      "app.header.more.export": "Export Document",
      "app.header.more.import": "Import Document",
      "app.header.more.settings": "Settings",
      "app.header.more.about": "About Playspace",
      "app.header.more.clearAllStrokes": "Clear All Strokes",
      "app.header.more.clearAllStrokesFailed":
        "<h1>You can't do that.</h1><p>You are not the owner of this document.</p>",
      "app.ui.closeAction": "Close",
      "app.ui.OKaction": "OK",
      "app.ui.loadingAction": "Loading...",
      "app.sharemodule.beginsharing": "Share this document",
      "app.sharemodule.editProfile": "Edit my Whiteboard Profile",
      "app.sharemodule.endsharing": "End share session",
      "app.sharemodule.copyLink": "Copy link",
      "app.sharemodule.copyLinkTitle": "Here's your link:",
      "app.sharemodule.copyLinkBody":
        "Use this link to join this document.<br/>This link will expire when you stop sharing, or when everyone has closed this document.",
      "app.tool.colorList.changeColor": "Change Color",
      "app.tool.colorList.black": "Black",
      "app.tool.colorList.red": "Red",
      "app.tool.colorList.pink": "Pink",
      "app.tool.colorList.purple": "Purple",
      "app.tool.colorList.indigo": "Indigo",
      "app.tool.colorList.blue": "Blue",
      "app.tool.colorList.cyan": "Cyan",
      "app.tool.colorList.teal": "Teal",
      "app.tool.colorList.green": "Green",
      "app.tool.colorList.lime": "Lime",
      "app.tool.colorList.yellow": "Yellow",
      "app.tool.colorList.orange": "Orange",
      "app.ui.dock.moreOptions": "More options",
      "app.ui.dockAlignment.bottom": "Align dock to bottom",
      "app.ui.dockAlignment.left": "Align dock to left",
      "app.ui.dockAlignment.right": "Align dock to right",
      "app.ui.zoom.in": "Zoom in",
      "app.ui.zoom.out": "Zoom out",
      "app.ui.zoom.resetZoom": "Reset Zoom",
      "app.signalbars.cloudDisconnected": "Not connected to Playspace Cloud",
      "app.signalbars.signalDisconnected": "Disconnected",
      "app.signalbars.cloudConnecting": "Connecting to Playspace Cloud...",
      "app.signalbars.cloudConnected": "Connected to Playspace Cloud",
      "app.signalbars.signalMSUnits": "ms",
      "app.signalbars.signalConnected": "Latency: ",
      "app.signalbars.signalLatencyWaiting":
        "Waiting for latency measurements...",
      "app.signalbars.signalLatencyError": "Latency measurement timeout...",
    },
  },
};
export default langs;
